services:
  db:
    image: mysql:8.0
    container_name: notes_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: notes_db
      MYSQL_USER: notes_user
      MYSQL_PASSWORD: notes_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notes_web
    restart: unless-stopped
    ports:
      - "5001:5000"   # если этот порт будет занят, можете заменить на "5001:5000"
    depends_on:
      - db
    environment:
      # Теперь контейнер web поймёт, что ему нужно подключаться к mysql://notes_user:notes_pass@db:3306/notes_db
      DATABASE_URL: "mysql+pymysql://notes_user:notes_pass@db:3306/notes_db"
      FLASK_ENV: production
      FLASK_APP: manage.py

volumes:
  db_data: